name: flow test
on:
    workflow_dispatch:
        inputs:
            pass-unit-test:
                type: boolean
                description: whether unit tests will pass or not
                default: true


jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "lint test"
    unit-test:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: unit test
              run: echo "running tests"
            - name: status check
              if: ${{!inputs.pass-unit-test}}
              run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-test
        steps:
            - name: delpoy non-prod
              run: echo "deploy noprod"
    e2e-test:
        runs-on: ubuntu-latest
        environment: staging
        needs: 
            - deploy-nonprod
        steps:
            - name: test if
              if: ${{vars.STAGING_VAR}} == '2000'
              run: |
                echo "ok e2e test"

    deploy-prod:
        runs-on: ubuntu-latest
        environment: prod
        needs:
            - e2e-test
            - deploy-nonprod
        steps:
            - name: deploy prod
              if: ${{success()}}
              run: echo "success.."
