name: test outputs
on: 
    push:
    workflow_dispatch:
        inputs: 
            test: 
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    output_job:
        runs-on: ubuntu-latest
        outputs:
            name: ${{ steps.test1.outputs.status }}
        steps:
            - name: print GITHUB_OUTPUT value
              run: echo "$GITHUB_OUTPUT"
            - name: test1
              id: test1
              run: |
                echo "status=${{inputs.test}}" >> "$GITHUB_OUTPUT"
                echo "$GITHUB_OUTPUT"
                echo "f1=one" >> "$GITHUB_OUTPUT"
                echo "Mistake=true" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
    one_more:
        runs-on: ubuntu-latest
        needs: output_job
        if: ${{needs.output_job.outputs.name == 'success' || needs.output_job.outputs.name == 'true'}}
        steps:
            - name: refer output job
              run: |
                echo "Byee - ${{needs.output_job.outputs.name}}"
                echo "Output"

