name: test outputs
on: 
    push:
    workflow_dispatch:
        inputs: 
            test: 
                type: boolean
                description: Test output
                default: false

jobs:
    output_job:
        runs-on: ubuntu-latest
        outputs:
            name: ${{ steps.test1.outputs.Name }}
        steps:
            - id: test1
              run: echo "Name=Sathish" >> "$GITHUB_OUTPUT"
    one_more:
        runs-on: ubuntu-latest
        needs: output_job
        steps:
            - name: refer output job
              run: echo "Byee - ${{needs.output_job.outputs.name}}"



