name: runner test
on: 
    #push
    workflow_dispatch
jobs:
    ubuntu_runner:
        runs-on: ubuntu-latest
        steps:
            - name: echo linx os
              run: |
                echo "job os test."
                echo "$RUNNER_OS"
    windows_runner:
        runs-on: windows-latest
        steps:
            - name: echo win os
              shell: bash
              run: |
                echo "job os test"
                echo "$RUNNER_OS"
    mac_runner:
        runs-on: macos-latest
        steps:
            - name: echo mac os
              #shell: bash
              run: |
                echo "job os test"
                echo "$RUNNER_OS"