name: Using Actions test
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 01-using-actions/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: install dep
              run: npm ci
            - name: run unit test
              run: npm run test


    



