name: var test 
on:
    push:
    workflow_dispatch:
env:
    test: "workflow"
    over: "testing workflow"
    undefined: ${{ vars.undefined || 'default value' }}
jobs:
    var_env:
        runs-on: ubuntu-latest
        env:
            test1: "job"
            over: "testing jobs"
        steps:
            - name: "test for env and var"
              env:
                   test2: "step"
              run: |
                echo "${{ env.test }} level"
                echo "${{ env.test1 }} level"
                echo "${{ env.test2 }} level"
                echo "${{ env.over }} level"
            - name: "test over value"
              run: echo "${{env.over}}"
    new_git_var:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: "prod var test"
              run: |
                echo "${{vars.prod_test}}"
                echo "${{vars.PROD_VAR}}"
                echo "${{vars.REPO_VAR}}"
    new_git:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: "prod var test"
              run: |
                echo "${{vars.staging_var}}"
                echo "${{vars.REPO_VAR}}"   
    non_check:
        runs-on: ubuntu-latest
        steps:
            - name: "non testing"
              run: |
                echo "${{env.undefined}}"

