name: workflow events usages
on: 
    pull_request:
    workflow_dispatch:

jobs:
    push_job:
        runs-on: ubuntu-latest
        steps:
            - name: show trigger
              run: echo "trigger by an ${{ github.event_name}} even."